// Most-used SAT words, ordered by importance. {w, pos, d, s}
// Add more here anytime — stages form automatically every 14 words.
export const WORDS = [
["advocate","v","to publicly support or argue for","Senators who advocate for the bill say it will reduce poverty."],
["undermine","v","to weaken","Constant criticism can undermine a student's confidence."],
["bolster","v","to strengthen or support","New evidence helped bolster the scientist's theory."],
["nuanced","adj","showing subtle distinctions","Her nuanced argument acknowledged both sides of the debate."],
["ambiguous","adj","open to more than one meaning","The poem's ambiguous ending left readers guessing."],
["arbitrary","adj","based on whim, not reason","The rule felt arbitrary, with no clear purpose."],
["plausible","adj","believable; reasonable","The detective offered a plausible explanation for the theft."],
["substantiate","v","to back up with evidence","The reporter could not substantiate the rumor."],
["refute","v","to prove false","The new study refutes the popular belief about the diet."],
["concede","v","to admit, often reluctantly","Even critics concede that the design is innovative."],
["pervasive","adj","spread throughout","Smartphones have a pervasive influence on daily life."],
["mitigate","v","to make less severe","Planting trees can mitigate the heat in crowded cities."],
["exacerbate","v","to make worse","Ignoring a small leak will only exacerbate the damage."],
["scrutinize","v","to examine closely","Editors scrutinize every claim before publishing it."],
["tenuous","adj","weak; flimsy","The link between the two events is tenuous at best."],
["inherent","adj","existing as a built-in quality","There are risks inherent in any experiment."],
["superfluous","adj","more than is needed","The essay improved once she cut the superfluous details."],
["paradox","n","a seemingly contradictory truth","It is a paradox that spending money can sometimes save it."],
["candor","n","honesty; frankness","She answered the hard questions with surprising candor."],
["skepticism","n","a doubting, questioning attitude","Scientists greeted the bold claim with skepticism."],
["pragmatic","adj","practical; focused on results","He took a pragmatic approach, choosing what actually worked."],
["ubiquitous","adj","found everywhere","Plastic packaging has become ubiquitous in stores."],
["anomaly","n","something that deviates from the norm","The unusually warm winter was an anomaly."],
["proliferate","v","to increase rapidly","Online courses proliferate whenever demand rises."],
["facilitate","v","to make easier","A good moderator can facilitate a productive discussion."],
["hinder","v","to slow down or block","Heavy rain can hinder a rescue effort."],
["curtail","v","to cut short; reduce","A drought may force a city to curtail water use."],
["endorse","v","to give public approval to","Several doctors endorse the new guidelines."],
["empirical","adj","based on observation or experiment","Empirical data, not opinion, settled the question."],
["derivative","adj","copied; unoriginal","Critics called the film derivative of older classics."],
["inevitable","adj","certain to happen","With steady practice, improvement is inevitable."],
["meticulous","adj","very careful and precise","She kept meticulous notes of every result."],
["redundant","adj","needlessly repetitive","Saying free gift is redundant."],
["viable","adj","workable; able to succeed","Solar power is now a viable energy source."],
["prudent","adj","cautious; sensible","It is prudent to save part of every paycheck."],
["indifferent","adj","showing no interest or concern","He was indifferent to the team's victory."],
["reconcile","v","to make two things consistent","It is hard to reconcile the two eyewitness accounts."],
["perpetuate","v","to keep something (often bad) going","Stereotypes in media can perpetuate prejudice."],
["diminish","v","to make or become smaller","Fame did not diminish her work ethic."],
["attribute","v","to credit a cause or source","Experts attribute the decline to overfishing."],
["discern","v","to detect or distinguish","It was hard to discern the truth from the rumors."],
["cohesive","adj","well-unified; sticking together","A cohesive essay flows from one idea to the next."],
["inconsequential","adj","unimportant; insignificant","The error was inconsequential and changed nothing."],
["ameliorate","v","to make a bad situation better","The new policy aims to ameliorate traffic."],
["innocuous","adj","harmless","The comment was innocuous, meant only as a joke."],
["ambivalent","adj","having mixed feelings","She felt ambivalent about moving to a new city."],
["contempt","n","scorn; strong disrespect","He looked at the cheater with contempt."],
["quotidian","adj","ordinary; everyday","The diary records quotidian details of farm life."],
["overt","adj","open; not hidden","There was no overt sign of trouble."],
["sanction","n","official approval (or a penalty, by context)","The committee gave its sanction to the plan."],
["postulate","v","to assume or put forward as true","Scientists postulate that the universe is expanding."],
["antagonistic","adj","hostile; opposed","The two nations had long been antagonistic."],
["supersede","v","to replace as superior","The new model will supersede last year's version."],
["preclude","v","to prevent; rule out","A tight budget can preclude a long vacation."],
["volatile","adj","unstable; quick to change","Stock prices were volatile all week."],
["autonomous","adj","independent; self-governing","The region became autonomous after the treaty."],
["fluctuate","v","to rise and fall irregularly","Temperatures fluctuate sharply in the desert."],
["comprehensive","adj","complete; covering everything","The report gave a comprehensive review of the data."],
["compelling","adj","convincing; persuasive","She made a compelling case for change."],
["coherent","adj","logically connected; clear","His argument was clear and coherent."],
["disparate","adj","fundamentally different","The class brought together students from disparate backgrounds."],
["negligible","adj","so small it can be ignored","The cost difference was negligible."],
["intrinsic","adj","belonging naturally; essential","Curiosity has intrinsic value in learning."],
["speculative","adj","based on guessing","The theory is still speculative."],
["didactic","adj","intended to teach","The novel is didactic, full of moral lessons."],
["aesthetic","adj","relating to beauty or art","The building's aesthetic appeal drew many visitors."],
["reverence","n","deep respect","She spoke of her old teacher with reverence."],
["nostalgia","n","a longing for the past","Old songs filled him with nostalgia."],
["apprehension","n","anxiety; worry","She felt apprehension before the big exam."],
["candid","adj","honest and direct","In a candid interview, the star admitted her mistakes."],
["yield","v","to produce, or to give way","Careful experiments often yield surprising results."],
["foster","v","to encourage the growth of","Good teachers foster a love of reading."],
["augment","v","to add to; increase","He works a second job to augment his income."],
["alleviate","v","to ease or lessen","This medicine can alleviate her pain."],
["impede","v","to obstruct","Fallen trees can impede traffic."],
["corroborate","v","to confirm with more evidence","A second witness can corroborate her story."],
["elucidate","v","to make clear; explain","The diagram helps elucidate how the engine works."],
["tentative","adj","hesitant; not certain","They reached a tentative agreement."],
["robust","adj","strong; well-supported","The findings rest on robust evidence."],
["unprecedented","adj","never done or seen before","The storm caused unprecedented damage."],
["conventional","adj","traditional; standard","She rejected conventional methods for a new approach."],
["marginal","adj","small; on the edge","The change made only a marginal difference."],
["synthesize","v","to combine into a whole","A strong essay synthesizes several sources."],
["enumerate","v","to list one by one","The guide enumerates every step in order."],
];
